version: '3.8'

services:
  spark-container:
    image: spark-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-container
    depends_on:
      - spark-master
    restart: unless-stopped
    volumes:
      - ./:/src/
